version: '2.1'

services:

  users-service:
    container_name: users-service
    build: .
      # dockerfile: Dockerfile-local
    # volumes:
    #   - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig


  web-service:
    container_name: web-service
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL==${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service